### ISSUE TITLE
Error: Synchronization — Extended Relationships

### ISSUE THREAD

**Issue by SnarfW** [ric2016/extended_relationships#1]
I get the following error with the "synchronization - extended relationship" option. Please advise how to solve this error. 

/home/xxxxxxxx/domains/bfle.nl/public_html/stamboom/modules_v3/extended_relationships/Sync.php:205 Class 'Cissee\Webtrees\Module\ExtendedRelationships\PDO' not found #0 /modules_v3/extended_relationships/Sync.php:44 Error("Class 'Cissee\Webtrees\Module\ExtendedRelationships\PDO' not found") #1 /modules_v3/extended_relationships/module.php:385 sync() #2 /module.php:26 modAction('sync')

**Comment by ric2016** [comment]
Thanks for the report! 
This is now fixed in the latest version (missing import statement in Sync.php).
