### ISSUE TITLE
Relationship to me - mark the extended version

### ISSUE THREAD

**Issue by HonkXL** [ric2016/extended_relationships#6]
I don't like to disable the original relationship to me, but I like the one from you. But in the menu both have the same name (see screenshot). In the settings of the module I set 	Include the ⚶ symbol in the module title to yes,
but it seems not to work.

<img width="154" alt="chart-menu" src="https://user-images.githubusercontent.com/16715040/52539913-da6c3100-2d83-11e9-9f34-f7e18cdfe54d.png">

**Comment by ric2016** [comment]
The setting 'Include the ⚶ symbol in the module title' is just for the module title in the control panel.
For the chart menu element name, use the setting 'Include the ⚶ symbol in the chart menu entry'.
(in webtrees 1.x, we can use different names for these, as opposed to e.g. tabs)

**Comment by ric2016** [comment]
In any case, the chart is intended as a replacement for the original chart. Is there a particular reason to keep the original chart as well?
